name: walkGreen

channels:
- conda-forge
- win-64
- r

dependencies:
- python=3.5
# r dependencies
- zeromq
# - readline
- pcre
- r
- r-essentials

# python dependencies
- numpy
- pandas
- pip
- jupyter
- iris